// <auto-generated />
namespace NTC.BusinessEntities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removeMemIdfromNotice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeMemIdfromNotice));
        
        string IMigrationMetadata.Id
        {
            get { return "201804090802161_removeMemIdfromNotice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
